name: Fetch and build Blog
description: Fetch and build the blog
inputs:
  token:
      description: 'The token to use for fetching the repository'
      required: true
  branch:
    description: 'The branch to fetch for blog content'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: 'zatsit-oss/zats-blog'
        token: ${{ inputs.token }}
        path: .

    - name: Checkout blog contents
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        path: blog-contents
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          blog
          docs

    - run: |
        ls -la
        ls -la blog-contents
      shell: bash

    - name: move blog-content blog dir to blog dir
      run: cp -R blog-contents/blog/* blog
      shell: bash

    - name: move blog-content docs dir to docs dir
      run: cp -R blog-contents/docs/* docs
      shell: bash

    - name: remove blog-content dir
      run: rm -R blog-contents
      shell: bash

    - name: node-setup
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - shell: bash
      run: npm ci

    - shell: bash
      run: npm run docusaurus build

