---
name: Fetch and build Blog
description: Fetch and build the blog
inputs:
  token:
    description: 'The token to use for fetching the repository'
    required: true
  branch:
    description: 'The branch to fetch for blog content'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout zatsit-blog repository
      uses: actions/checkout@v4
      with:
        repository: 'zatsit-oss/zats-blog'
        token: ${{ inputs.token }}
        path: .

    - name: Checkout zatsit-blog-content repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        token: ${{ inputs.token }}
        fetch-depth: 0
        path: blog-contents

    - name: Copy blog-content to blog
      shell: bash
      run: |
        cp blog-contents/{docusaurus.config.js,firebase.json,.firebaserc} .
        cp -R blog-contents/blog/* blog
        cp -R blog-contents/docs/* docs
        cp blog-contents/authors/authors.yml blog
        cp -R blog-contents/authors/img/* static/img/authors
        rm -R blog-contents

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install npm dependencies
      shell: bash
      run: |
        npm ci

    - shell: bash
      run: npm run build
