---
name: Deploy to Firebase Hosting on PR

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "blog/**"
      - "docs/**"
      - "docusaurus.config.js"

permissions:
  checks: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch and Build blog content
        uses: ./.github/actions/docusaurus
        with:
          token: ${{ secrets.GH_PAT }}
          branch: ${{ github.head_ref || github.ref_name }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZATSIT_BLOG_STAGING }}
          projectId: zatsit-dsi-externalsites-dev
          target: zatsit-blog-b5294
          expires: 30d

      # needed to avoid the post action error
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
