name: Update training repo on merge

on:
  push:
    branches:
      - main
    paths:
      - "blog/**"
      - "docs/**"
  workflow_dispatch:


concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  update-training-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Force Push changes on content-training
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          repository: zatsit-oss/zats-blog-content-training
          branch: main_training
          force: true

